### ISSUE TITLE
[META] Andino release via ROS

### ISSUE THREAD

**Issue by francocipollone** [Ekumen-OS/andino#154]
### Summary

Let's release andino repos!

### Docs
https://docs.ros.org/en/humble/How-To-Guides/Releasing/Releasing-a-Package.html
http://wiki.ros.org/buildfarm/Pull%20request%20testing
https://docs.ros.org/en/eloquent/Tutorials/Releasing-a-ROS-2-package-with-bloom.html

### PreTasks
 - [x] Verify naming conventions/licensing / etc
 - [x] https://github.com/Ekumen-OS/andino/pull/153
 - #155 
 - #156 
 - https://github.com/Ekumen-OS/andino/pull/157
 - #161 
 - #163
### Tasks

- [x] Add andino entry point to humble index
     - https://github.com/ros/rosdistro/pull/38645
- [x] Add andino team and create release repo at https://github.com/ros2-gbp/ros2-gbp-github-org
     - https://github.com/ros2-gbp/ros2-gbp-github-org/issues/338
- [x] Link jenkins build with github. http://wiki.ros.org/buildfarm/Pull%20request%20testing
- [x] Bloom release https://github.com/ros/rosdistro/pull/38739

**Comment by francocipollone** [comment]
In order to enable the pull request testing to be linked with the Pull request we have to give at least `write` access to the `ros-pull-request-builder` user to the `Ekumen-OS` organization as indicated here: http://wiki.ros.org/buildfarm/Pull%20request%20testing

@jballoffet I think that this is another reason to go with a separate organization. wdyt?

**Comment by francocipollone** [comment]
Anyway, we might still not needed, I will need to double check with some ros folks:

I imagine if the invitation gets approved for this repo only it will be enough.
![image](https://github.com/Ekumen-OS/andino/assets/53065142/258c8d54-a9fd-4367-abeb-6df42c2e4bc6)

**Comment by jballoffet** [comment]
Got it, sounds good!

**Comment by francocipollone** [comment]
https://github.com/ros/rosdistro/pull/38739

**Comment by francocipollone** [comment]
Closed as completed
