### ISSUE TITLE
Provide a gazebo simulation

### ISSUE THREAD

**Issue by francocipollone** [Ekumen-OS/andino#47]
## Context
We already have a gazebo simulation at noetic branch but it was an old implementation. The urdf description way different than the current one.

## Summary
 - Create gazebo ROS2 simulation
 - Gracefully deal with urdf descriptions for:
   - real robot (ros2_control)
   - simulation using ros2_control
   - simulation using diff_drive plugin. (long shot, might not be necessary)

## Notes
 - an `andino_gazebo` package is expected to be created
 - I expect no gazebo references to andino_description's urdf description. Gazebo references should be part of the andino_gazebo package.

**Comment by Voldivh** [comment]
## Task Description
Taking into account the initial issue description and that we have started working in doing a contribution for this issue, we have defined the following task in order to accomplish the 

- [ ] The robot model for the Andino bot is included in the simulation environment within Gazebo Classic.
- [ ] The robot should be integrated with the following sensors:
- Wheel encoders
- Camera
- Lidar
- IMU (**if determined necessary, taking into account that the physical version of the Andino does not have an IMU**)
- [ ] Use ROS 2 Control to move the robot's wheels.
- [ ] Generate a launch file that is able to start the Gazebo simulation with the Andino bot in a environment.

### Notes
This feature should be implemented as a standalone package.

**Comment by francocipollone** [comment]
Hey there I have some pointers on this topic.

## Implementation Suggestion

### URDF
- `andino_description` contains the description of the robot. I'd recommend not adding gazebo references within `andino_description` in order to make it simulator agnostic.
For so, I'd recommend having a xacro file within `andino_gazebo` package that include the main xacro from `andino_description` and add the gazebo references that this needs.

### ROS 2 control
Use https://github.com/ros-controls/gazebo_ros2_control . This package provides the "gazebo hardware interface" to be used between the diff drive controller and gazebo

### Sensors
IMU isn't part of the robot or the description yet. It's ok to add the IMU to the description, however, I'd suggest doing it in two steps. First, make sure the simulation is working with what you have as it is, and then, as a second step/enhacenment we can add the IMU to the description and the correspondent IMU controller(for gazebo).

**Comment by agalbachicar** [comment]
@olmerg this ticket has been closed but I want to confirm:

- Have we decided to include the camera?
- Is ROS 2 Control finally working with the closed PR?
